### ISSUE TITLE
Add an AppVeyor initial script

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/cookiecutter-pytest-plugin#9]
Add a template for an `appveyor.yml` file similar to `.travis.yml`.

**Note**: A lot of projects out there copy/paste a `install.ps1` script and use that within the `appveyor.yml` file, but if you don't need py26 support this is not necessary because AppVeyor VMs come with py27, py32, py33, py34 and py35 pre-installed so it is just a matter of calling `tox` from one of those python versions.

For example:

```yml
install:
  - set PATH=C:\Python35;C:\Python35\Scripts;%PATH%
  - python -m pip install tox

build: false  # Not a C# project

test_script:
  - tox -e py27,py32,py33,py34,py35
```
